---
# Initial Server Setup
remote_user: ishmael

# MySQL Setup
mysql_root_password: MikelArteta
# mysql_root: MikelArteta
mysql_app_db: bare_server
mysql_app_user: bare_server_user
mysql_app_pass: MikelArteta

# Web Server Setup
http_host: "{{ ansible_default_ipv4.address }}"
remote_www_root: /var/www
app_root_dir: bare_server
document_root: "{{ remote_www_root }}/{{ app_root_dir }}/public"

# Laravel Env Variables
app_name: "Server-Auto-Deploy"
app_env: dev
app_debug: true
app_url: "http://{{ http_host }}"
db_host: localhost
db_port: 3306
db_database: "{{ mysql_app_db }}"
db_user: "{{ mysql_app_user }}"
db_pass: "{{ mysql_app_pass }}"