---
- hosts: all
  become: true
  tasks:
    # Other tasks here...

    - name: Upgrade PHP to 8.2 or latest
      apt:
        name: "{{ php_upgrade_package }}"
        state: latest
        update_cache: yes
      when: php.module_version.php | version_compare('<', '8.2')  # Use filter without Jinja2 delimiters
      vars:
        php_upgrade_package: php  # Adjust for your specific packages if needed

      tags:
        - php_upgrade





