---
- name: Check if Composer is installed
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Check if Composer is installed
      shell: command -v composer
      register: composer_installed
      changed_when: false
      ignore_errors: true

    - name: Install Composer if not already installed
      block:
        - name: Download Composer installer
          get_url:
            url: https://getcomposer.org/installer
            dest: /tmp/composer-setup.php
          when: composer_installed.rc != 0

        - name: Install Composer
          shell: php /tmp/composer-setup.php -- --install-dir=/usr/local/bin --filename=composer
          args:
            executable: /bin/bash
          when: composer_installed.rc != 0
